# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod 'EasyTipView', '~> 0.1.3'
end
