# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fibonacci' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fibonacci
  pod 'BigInt', :git => 'https://github.com/lorentey/BigInt.git'

  target 'FibonacciTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FibonacciUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
